
name: Analyze and PR to Tradier Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 1-5'  # Corre a las 10AM UTC (5AM CDT) lunes a viernes

jobs:
  analyze-and-pr:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TRADIER_REPO: "https://github.com/tbarato1804/tradier.git"

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: pip install openai black

      - name: Clonar repo Tradier
        run: git clone $TRADIER_REPO tradier

      - name: Analizar errores (simulaci칩n)
        run: |
          echo '{ "error": "ImportError: cannot import name XYZ", "description": "El m칩dulo ABC no tiene XYZ" }' > tradier/result.json

      - name: Obtener sugerencia de OpenAI
        run: |
          python analyze_tradier.py tradier/result.json > tradier/suggestion.txt

      - name: Validar con black
        run: |
          black tradier/suggestion.txt || echo "丘멆잺 Formato no v치lido, pero contin칰a"

      - name: Aplicar sugerencia como Pull Request
        run: |
          cd tradier
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -b suggestion-patch-$(date +%s)
          echo "# GPT Suggestion" >> gpt_patch.py
          cat suggestion.txt >> gpt_patch.py
          git add gpt_patch.py
          git commit -m "游눠 Sugerencia autom치tica de OpenAI [skip ci]"
          git push origin HEAD
          gh pr create --title "Sugerencia de GPT" --body "Esta PR contiene una mejora sugerida autom치ticamente por OpenAI." --head "$(git rev-parse --abbrev-ref HEAD)"
