name: Apply GPT Patch Manually

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Rama con la sugerencia (ej: suggestion-patch-17018xxxx)'
        required: true

jobs:
  apply-patch:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TRADIER_TOKEN: ${{ secrets.TRADIER_TOKEN }}

    steps:
      - name: Clonar repositorio Tradier y cambiar a la rama
        run: |
          git clone https://x-access-token:${{ secrets.TRADIER_TOKEN }}@github.com/tbarato1804/tradier.git tradier
          cd tradier
          git checkout ${{ github.event.inputs.branch }}

      - name: Verificar sintaxis del parche
        id: syntax
        run: |
          cp tradier/gpt_patch.py tradier/gpt_patch_temp.py
          python -m py_compile tradier/gpt_patch_temp.py && echo "ok=true" >> $GITHUB_OUTPUT || echo "ok=false" >> $GITHUB_OUTPUT

      - name: Aplicar parche si pasa verificación
        if: steps.syntax.outputs.ok == 'true'
        run: |
          cp tradier/gpt_patch_temp.py tradier/applied_patch.py
          echo "✅ Patch aplicado correctamente."

      - name: Comentar en el Pull Request si falla
        if: steps.syntax.outputs.ok != 'true'
        run: |
          gh auth setup-git
          cd tradier
          PR_URL=$(gh pr list --head "${{ github.event.inputs.branch }}" --json url -q '.[0].url')
          gh pr comment "$PR_URL" --body "❌ El parche no fue aplicado automáticamente porque contiene errores de sintaxis en \`gpt_patch.py\`.

Puedes revisarlo manualmente o corregirlo antes de aplicarlo."

      - name: Subir archivos como artefactos
        uses: actions/upload-artifact@v4
        with:
          name: gpt_patch_manual
          path: |
            tradier/gpt_patch.py
            tradier/gpt_patch_temp.py
            tradier/applied_patch.py
          if-no-files-found: warn
